import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
import { styled } from '@mui/material/styles';
import Toolbar from '@mui/material/Toolbar';
import Head from 'next/head';
import Image from 'next/image';
import MenuTile from '../components/MenuTile';
import SearchField from '../components/SearchField';

const FullscreenWrapper = styled(Box)(({ theme }) => ({
  minHeight: '100vh',
  display: 'flex',
  flexDirection: 'column',
  backgroundColor: theme.palette.primary.main,
  color: theme.palette.common.white,
}));

const StyledContainer = styled(Container)(({ theme }) => ({
  flex: 1,
  padding: theme.spacing(4),
}));

const Home = () => {
  return (
    <FullscreenWrapper>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <AppBar position='static' elevation={0}>
        <Toolbar>
          <Image src='/logo.svg' width='118px' height='50px' />
          <SearchField />
        </Toolbar>
      </AppBar>
      <StyledContainer maxWidth='md'>
        <Grid container spacing={4}>
          <Grid item xs={6} sm={4} md={3}>
            <MenuTile imageUrl='/icons/window.svg' title='OKNÁ' width='100px' />
          </Grid>
          <Grid item xs={6} sm={4} md={3}>
            <MenuTile imageUrl='/icons/door.svg' title='DVERE' width='100px' />
          </Grid>
          <Grid item xs={6} sm={4} md={3}>
            <MenuTile
              imageUrl='/icons/other.svg'
              title='PRÍSLUŠENSTVO'
              width='100px'
            />
          </Grid>
        </Grid>
      </StyledContainer>
    </FullscreenWrapper>
  );
};

export default Home;
